# Generated by Django 3.2.4 on 2021-06-14 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='The name of the list.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='The description of the list.', max_length=318, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='The owner of the list.', on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='The name of the item.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='The description of the item.', max_length=318, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('todolist', models.ForeignKey(help_text='The list of the item.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='list.todolist')),
            ],
        ),
    ]
